apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  labels:
    env: monitor
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: task-pv-container
      image: rintucmathew/httpd
      ports:
        - containerPort: 8080
          name: "Appache-server"
      volumeMounts:
        - mountPath: "/var/www/html/"
                                       
          name: pv-storage
